[tool.poetry]
name = "pubmedfetcher"
version = "0.1.0"
description = "A tool to fetch research papers from PubMed"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28"
